#!/bin/bash
#SBATCH --partition=compute # Queue selection
#SBATCH --job-name=nuc_b # Job name
#SBATCH --mail-type=ALL# Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=dgellermcgrath@gmail.com # Where to send mail
#SBATCH --ntasks=1 # Run on one CPU
#SBATCH --nodes=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=180gb # Job memory request
#SBATCH --time=2-00:00:00 # Time limit hrs:min:sec
#SBATCH --output=logs/nucmer_b_%j.log# Standard output/error
#SBATCH --qos=unlim
#
cd /vortexfs1/scratch/dgellermcgrath
#
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_568 draft_mags/CarAnox_mtb2_568.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1544 draft_mags/CarAnox_mtb2_1544.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_206 draft_mags/CarAnox_mtb2_206.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_535 draft_mags/CarAnox_mtb2_535.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_638 draft_mags/CarAnox_mtb2_638.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_864 draft_mags/CarAnox_mtb2_864.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_120 draft_mags/CarAnox_mtb2_120.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_239 draft_mags/CarAnox_mtb2_239.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1543 draft_mags/CarAnox_mtb2_1543.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_658 draft_mags/CarAnox_mtb2_658.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_406 draft_mags/CarAnox_mtb2_406.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_832 draft_mags/CarAnox_mtb2_832.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_916 draft_mags/CarAnox_mtb2_916.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_879 draft_mags/CarAnox_mtb2_879.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1162 draft_mags/CarAnox_mtb2_1162.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_218 draft_mags/CarAnox_mtb2_218.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1208 draft_mags/CarAnox_mtb2_1208.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_530 draft_mags/CarAnox_mtb2_530.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1036 draft_mags/CarAnox_mtb2_1036.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_198 draft_mags/CarAnox_mtb2_198.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1601 draft_mags/CarAnox_mtb2_1601.fa Planctomycetota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_42 draft_mags/CarAnox_mtb2_42.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_109 draft_mags/CarAnox_mtb2_109.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_59 draft_mags/CarAnox_mtb2_59.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_106 draft_mags/CarAnox_mtb2_106.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_46 draft_mags/CarAnox_mtb2_46.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_112 draft_mags/CarAnox_mtb2_112.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_857 draft_mags/CarAnox_mtb2_857.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_598 draft_mags/CarAnox_mtb2_598.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_610 draft_mags/CarAnox_mtb2_610.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_722 draft_mags/CarAnox_mtb2_722.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_885 draft_mags/CarAnox_mtb2_885.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1374 draft_mags/CarAnox_mtb2_1374.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1263 draft_mags/CarAnox_mtb2_1263.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_757 draft_mags/CarAnox_mtb2_757.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_768 draft_mags/CarAnox_mtb2_768.fa Patescibacteria.fa
