#!/bin/bash
#SBATCH --partition=compute # Queue selection
#SBATCH --job-name=nuc_k # Job name
#SBATCH --mail-type=ALL# Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=dgellermcgrath@gmail.com # Where to send mail
#SBATCH --ntasks=1 # Run on one CPU
#SBATCH --nodes=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=180gb # Job memory request
#SBATCH --time=2-00:00:00 # Time limit hrs:min:sec
#SBATCH --output=logs/nucmer_k_%j.log# Standard output/error
#SBATCH --qos=unlim
#
cd /vortexfs1/scratch/dgellermcgrath
#
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_451 draft_mags/CarAnox_mtb2_451.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1251 draft_mags/CarAnox_mtb2_1251.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_343 draft_mags/CarAnox_mtb2_343.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1396 draft_mags/CarAnox_mtb2_1396.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_729 draft_mags/CarAnox_mtb2_729.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_171 draft_mags/CarAnox_mtb2_171.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_361 draft_mags/CarAnox_mtb2_361.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1636 draft_mags/CarAnox_mtb2_1636.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_650 draft_mags/CarAnox_mtb2_650.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_754 draft_mags/CarAnox_mtb2_754.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_504 draft_mags/CarAnox_mtb2_504.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1365 draft_mags/CarAnox_mtb2_1365.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1264 draft_mags/CarAnox_mtb2_1264.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1398 draft_mags/CarAnox_mtb2_1398.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_975 draft_mags/CarAnox_mtb2_975.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1684 draft_mags/CarAnox_mtb2_1684.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_214 draft_mags/CarAnox_mtb2_214.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_236 draft_mags/CarAnox_mtb2_236.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_880 draft_mags/CarAnox_mtb2_880.fa Desulfobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1083 draft_mags/CarAnox_mtb2_1083.fa Campylobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_654 draft_mags/CarAnox_mtb2_654.fa Campylobacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_216 draft_mags/CarAnox_mtb2_216.fa Poribacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_128 draft_mags/CarAnox_mtb2_128.fa Margulisbacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1352 draft_mags/CarAnox_mtb2_1352.fa Margulisbacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1367 draft_mags/CarAnox_mtb2_1367.fa Margulisbacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_310 draft_mags/CarAnox_mtb2_310.fa Margulisbacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_739 draft_mags/CarAnox_mtb2_739.fa Margulisbacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1288 draft_mags/CarAnox_mtb2_1288.fa Margulisbacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_116 draft_mags/CarAnox_mtb2_116.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_974 draft_mags/CarAnox_mtb2_974.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_586 draft_mags/CarAnox_mtb2_586.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_329 draft_mags/CarAnox_mtb2_329.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_779 draft_mags/CarAnox_mtb2_779.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1039 draft_mags/CarAnox_mtb2_1039.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_719 draft_mags/CarAnox_mtb2_719.fa Iainarchaeota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_718 draft_mags/CarAnox_mtb2_718.fa Iainarchaeota.fa
