#!/bin/bash
#SBATCH --partition=compute # Queue selection
#SBATCH --job-name=nuc_d # Job name
#SBATCH --mail-type=ALL# Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=dgellermcgrath@gmail.com # Where to send mail
#SBATCH --ntasks=1 # Run on one CPU
#SBATCH --nodes=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=180gb # Job memory request
#SBATCH --time=2-00:00:00 # Time limit hrs:min:sec
#SBATCH --output=logs/nucmer_d_%j.log# Standard output/error
#SBATCH --qos=unlim
#
cd /vortexfs1/scratch/dgellermcgrath
#
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1199 draft_mags/CarAnox_mtb2_1199.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1249 draft_mags/CarAnox_mtb2_1249.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_207 draft_mags/CarAnox_mtb2_207.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_151 draft_mags/CarAnox_mtb2_151.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1515 draft_mags/CarAnox_mtb2_1515.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1219 draft_mags/CarAnox_mtb2_1219.fa KSB1.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_810 draft_mags/CarAnox_mtb2_810.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1576 draft_mags/CarAnox_mtb2_1576.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_213 draft_mags/CarAnox_mtb2_213.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_315 draft_mags/CarAnox_mtb2_315.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1507 draft_mags/CarAnox_mtb2_1507.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1194 draft_mags/CarAnox_mtb2_1194.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_983 draft_mags/CarAnox_mtb2_983.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_773 draft_mags/CarAnox_mtb2_773.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1148 draft_mags/CarAnox_mtb2_1148.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_347 draft_mags/CarAnox_mtb2_347.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_713 draft_mags/CarAnox_mtb2_713.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_957 draft_mags/CarAnox_mtb2_957.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_335 draft_mags/CarAnox_mtb2_335.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1173 draft_mags/CarAnox_mtb2_1173.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_771 draft_mags/CarAnox_mtb2_771.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_595 draft_mags/CarAnox_mtb2_595.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1375 draft_mags/CarAnox_mtb2_1375.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1524 draft_mags/CarAnox_mtb2_1524.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_281 draft_mags/CarAnox_mtb2_281.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1540 draft_mags/CarAnox_mtb2_1540.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_187 draft_mags/CarAnox_mtb2_187.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_193 draft_mags/CarAnox_mtb2_193.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_945 draft_mags/CarAnox_mtb2_945.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_205 draft_mags/CarAnox_mtb2_205.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_209 draft_mags/CarAnox_mtb2_209.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_606 draft_mags/CarAnox_mtb2_606.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1146 draft_mags/CarAnox_mtb2_1146.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1447 draft_mags/CarAnox_mtb2_1447.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1583 draft_mags/CarAnox_mtb2_1583.fa Proteobacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1239 draft_mags/CarAnox_mtb2_1239.fa Proteobacteria.fa
