#!/bin/bash
#SBATCH --partition=compute # Queue selection
#SBATCH --job-name=nuc_c # Job name
#SBATCH --mail-type=ALL# Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=dgellermcgrath@gmail.com # Where to send mail
#SBATCH --ntasks=1 # Run on one CPU
#SBATCH --nodes=1
#SBATCH --cpus-per-task=36
#SBATCH --mem=180gb # Job memory request
#SBATCH --time=2-00:00:00 # Time limit hrs:min:sec
#SBATCH --output=logs/nucmer_c_%j.log# Standard output/error
#SBATCH --qos=unlim
#
cd /vortexfs1/scratch/dgellermcgrath
#
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_463 draft_mags/CarAnox_mtb2_463.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1279 draft_mags/CarAnox_mtb2_1279.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_944 draft_mags/CarAnox_mtb2_944.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1600 draft_mags/CarAnox_mtb2_1600.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1089 draft_mags/CarAnox_mtb2_1089.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1098 draft_mags/CarAnox_mtb2_1098.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1438 draft_mags/CarAnox_mtb2_1438.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_422 draft_mags/CarAnox_mtb2_422.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1363 draft_mags/CarAnox_mtb2_1363.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_15 draft_mags/CarAnox_mtb2_15.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_959 draft_mags/CarAnox_mtb2_959.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1509 draft_mags/CarAnox_mtb2_1509.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1121 draft_mags/CarAnox_mtb2_1121.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_538 draft_mags/CarAnox_mtb2_538.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1552 draft_mags/CarAnox_mtb2_1552.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_68 draft_mags/CarAnox_mtb2_68.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_614 draft_mags/CarAnox_mtb2_614.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1465 draft_mags/CarAnox_mtb2_1465.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_690 draft_mags/CarAnox_mtb2_690.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_790 draft_mags/CarAnox_mtb2_790.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_692 draft_mags/CarAnox_mtb2_692.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1067 draft_mags/CarAnox_mtb2_1067.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1527 draft_mags/CarAnox_mtb2_1527.fa Patescibacteria.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1512 draft_mags/CarAnox_mtb2_1512.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_14 draft_mags/CarAnox_mtb2_14.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1562 draft_mags/CarAnox_mtb2_1562.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_809 draft_mags/CarAnox_mtb2_809.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1322 draft_mags/CarAnox_mtb2_1322.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1446 draft_mags/CarAnox_mtb2_1446.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1415 draft_mags/CarAnox_mtb2_1415.fa Latescibacterota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_877 draft_mags/CarAnox_mtb2_877.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_657 draft_mags/CarAnox_mtb2_657.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_756 draft_mags/CarAnox_mtb2_756.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_529 draft_mags/CarAnox_mtb2_529.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_453 draft_mags/CarAnox_mtb2_453.fa Krumholzibacteriota.fa
MUMmer3.23/nucmer --minmatch 500 -p hits/CarAnox_mtb2_1432 draft_mags/CarAnox_mtb2_1432.fa Krumholzibacteriota.fa
